name: ipyturtle_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - notebook=6.5  # klassische Notebook-Version für ipyturtle
  - ipywidgets=7.7
  - ipyturtle
  - pip
  - pip:
      - ipyturtle
